#!/bin/bash

echo "copy of jar file in docker-server/src"
cp QuizRouletteServer-build/QuizRouletteServer-code/target/QuizRouletteServer-code-1.0-SNAPSHOT-standalone.jar docker-server/src

echo "build of Dockerfile"
docker build -t labo2-server-java ./docker-server

echo "run image"
docker run -p 1313:1313 labo2-server-java
